### ISSUE TITLE
how do you create new questions and re arange

### ISSUE THREAD

**Issue by pxldevv** [hsnice16/forming-typeform#11]

**Comment by hsnice16** [comment]
Number of questions is static so I have hardcoded each question, which you can find in this component - https://github.com/hsnice16/forming-typeform/blob/main/components/main-content/MainContent.tsx

And to rearrange them, I am maintaining two state variables, **now** and **prev**.

**Comment by pxldevv** [comment]
Okay cool! Thanks, I will take a look tomorrow! Also love the fast response!
