### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by MoezGholami** [hsnice16/forming-typeform#12]
Hi,
Thanks for creating this package. Please add a license if you can. That way we can know how we can use your package. It should be as easy as copy & pasting a file.
You may find this guide helpful: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by hsnice16** [comment]
Hey, thanks for pointing this out @MoezGholami 
Let me check this.

**Comment by MoezGholami** [comment]
Thank you so much
